export type FieldScope = "root" | "rules" | "reward" | "content" | "cta"
export type FieldKind = "text" | "textarea" | "number" | "select" | "switch" | "date" | "tags" | "image"
export interface ContentField { key: string; label: string; scope: FieldScope; kind?: FieldKind; required?: boolean; items?: string[]; hint?: string; min?: number; max?: number }
export interface ContentTypeConfig { type: string; slug: string; title: string; singular: string; description: string; icon: string; accent: string; fields: ContentField[] }

const f = (scope: FieldScope, key: string, label: string, kind: FieldKind = "text", extra: Partial<ContentField> = {}): ContentField => ({ scope, key, label, kind, ...extra })
const common = [f("root", "title", "Başlık", "text", { required: true }), f("root", "slug", "Slug", "text", { required: true }), f("root", "subtitle", "Alt başlık"), f("root", "description", "Açıklama", "textarea"), f("root", "locale", "Dil", "select", { items: ["tr", "en", "de", "ru"] }), f("root", "order", "Sıra", "number", { min: 0 })]
const media = [f("root", "image", "Masaüstü görsel URL", "image"), f("root", "mobileImage", "Mobil görsel URL", "image")]
const schedule = [f("root", "startsAt", "Başlangıç", "date"), f("root", "endsAt", "Bitiş", "date")]
const cta = [f("cta", "label", "Buton metni"), f("cta", "href", "Buton bağlantısı")]
const reward = [f("reward", "type", "Ödül tipi", "select", { items: ["none", "balance", "bonus", "free-spins", "xp"] }), f("reward", "amount", "Ödül tutarı", "number", { min: 0 }), f("reward", "currency", "Ödül para birimi"), f("reward", "wageringMultiplier", "Çevrim katı", "number", { min: 0 })]

const configs: ContentTypeConfig[] = [
  // mission ve bonus JSON yerine MissionEditor/BonusEditor kullanır; buradaki
  // alanlar yalnızca liste tablosunun kolonlarını belirler ve backend
  // `casinoRewardSchema` sözleşmesiyle aynı anahtarları taşır.
  { type: "mission", slug: "missions", title: "Görevler", singular: "Görev", description: "Hedef, filtre, dönem ve ödül koşullarını ayrı ayrı yönetin.", icon: "tabler-target-arrow", accent: "primary", fields: [...common, f("rules", "eventType", "Etkinlik", "select", { required: true, items: ["deposit", "wager", "win", "game-round", "login"] }), f("rules", "target", "Hedef", "number", { required: true, min: 1 }), f("rules", "period", "Dönem", "select", { items: ["lifetime", "daily", "weekly", "monthly"] }), ...schedule, ...reward, ...cta] },
  { type: "bonus", slug: "bonuses", title: "Bonuslar", singular: "Bonus", description: "Aktivasyon, yatırım, çevrim ve teslim koşullarını yapılandırın.", icon: "tabler-gift", accent: "success", fields: [...common, ...media, f("rules", "activation", "Aktivasyon", "select", { required: true, items: ["deposit", "instant"] }), f("rules", "minimumDeposit", "Min. yatırım", "number", { min: 0 }), f("rules", "wagerMultiplier", "Çevrim", "number", { min: 0 }), ...schedule, ...reward, ...cta] },
  { type: "promotion", slug: "promotions", title: "Promosyonlar", singular: "Promosyon", description: "Kampanya kartları, hedef kitle, koşullar ve yayın takvimi.", icon: "tabler-speakerphone", accent: "warning", fields: [...common, ...media, f("root", "category", "Kategori"), f("content", "badge", "Rozet"), f("content", "terms", "Koşullar", "textarea"), f("rules", "audiences", "Hedef kitle", "tags"), ...schedule, ...cta] },
  { type: "referral-tier", slug: "referral-tiers", title: "Refer & Earn", singular: "Referans seviyesi", description: "Referans eşikleri, komisyon ve ödül seviyeleri.", icon: "tabler-users-group", accent: "info", fields: [...common, f("rules", "threshold", "Gereksinim / eşik", "number", { min: 0 }), f("content", "commissionRate", "Komisyon oranı (%)", "number", { min: 0, max: 100 }), ...reward] },
  { type: "vip-benefit", slug: "vip-benefits", title: "VIP Avantajları", singular: "VIP avantajı", description: "VIP sekmeleri, rank aralıkları ve avantaj koşulları.", icon: "tabler-crown", accent: "warning", fields: [...common, ...media, f("content", "group", "Sekme / grup"), f("rules", "minimumRank", "Minimum rank", "number", { min: 0 }), f("rules", "maximumRank", "Maksimum rank", "number", { min: 0 }), f("content", "conditions", "Koşulları göster", "switch")] },
  { type: "vip-manager", slug: "vip-managers", title: "VIP Yöneticileri", singular: "VIP yöneticisi", description: "Yönetici profilleri, iletişim bilgileri ve görsel kırpma.", icon: "tabler-user-star", accent: "primary", fields: [...common, ...media, f("content", "jobTitle", "Unvan"), f("content", "contact", "İletişim"), f("content", "cropLeft", "Kırpma sol", "number"), f("content", "cropTop", "Kırpma üst", "number"), ...cta] },
  { type: "vip-faq", slug: "vip-faq", title: "VIP SSS", singular: "VIP sorusu", description: "VIP üyelerine gösterilen soru, cevap ve kategoriler.", icon: "tabler-help-hexagon", accent: "info", fields: [f("root", "title", "Soru", "text", { required: true }), f("root", "slug", "Slug", "text", { required: true }), f("root", "description", "Cevap", "textarea", { required: true }), f("root", "category", "Kategori"), f("root", "locale", "Dil", "select", { items: ["tr", "en", "de", "ru"] }), f("root", "order", "Sıra", "number", { min: 0 })] },
  { type: "site-navigation", slug: "site-navigation", title: "Site Menüsü", singular: "Menü öğesi", description: "Masaüstü ve mobil navigasyon bağlantıları.", icon: "tabler-menu-2", accent: "primary", fields: [...common, f("content", "section", "Bölüm"), f("content", "href", "Bağlantı", "text", { required: true }), f("content", "icon", "İkon"), f("content", "parent", "Üst öğe"), f("rules", "requiresAuth", "Giriş gerekli", "switch"), f("content", "target", "Hedef", "select", { items: ["_self", "_blank"] }), f("content", "desktop", "Masaüstünde göster", "switch"), f("content", "mobile", "Mobilde göster", "switch")] },
  { type: "site-footer", slug: "site-footer", title: "Footer", singular: "Footer öğesi", description: "Footer kolonları, bağlantıları, sosyal ve yasal metinler.", icon: "tabler-layout-bottombar", accent: "secondary", fields: [...common, f("content", "group", "Kolon / grup"), f("content", "href", "Bağlantı"), f("content", "socialIcon", "Sosyal ikon"), f("content", "legalText", "Yasal metin", "textarea")] },
  { type: "help-article", slug: "help-articles", title: "Yardım Merkezi", singular: "Yardım makalesi", description: "Aranabilir yardım makaleleri ve ilişkili bağlantılar.", icon: "tabler-lifebuoy", accent: "info", fields: [...common, f("root", "category", "Kategori"), f("content", "answer", "Zengin cevap", "textarea", { required: true }), f("content", "keywords", "Anahtar kelimeler", "tags"), f("content", "links", "İlişkili bağlantılar", "tags")] },
  { type: "home-hero", slug: "home-heroes", title: "Ana Sayfa Hero", singular: "Hero", description: "Hero mesajı, görselleri, CTA ve yayın zamanlaması.", icon: "tabler-layout-dashboard", accent: "primary", fields: [...common, ...media, f("content", "badge", "Rozet"), f("content", "theme", "Tema", "select", { items: ["dark", "light", "brand"] }), f("content", "alignment", "Hizalama", "select", { items: ["left", "center", "right"] }), ...cta, ...schedule] },
  { type: "home-section", slug: "home-sections", title: "Ana Sayfa Bölümleri", singular: "Ana sayfa bölümü", description: "Ana sayfadaki dinamik bölüm kaynakları ve limitleri.", icon: "tabler-layout-rows", accent: "primary", fields: [...common, f("content", "sectionType", "Bölüm tipi", "select", { items: ["games", "providers", "promotions", "content"] }), f("content", "source", "Bağlı kaynak / filtre"), f("content", "limit", "Gösterim limiti", "number", { min: 1 })] },
  { type: "casino-rail", slug: "casino-rails", title: "Casino Rayları", singular: "Casino rayı", description: "Oyun raylarının seçim yöntemi, filtresi ve görünürlüğü.", icon: "tabler-carousel-horizontal", accent: "success", fields: [...common, f("content", "selectionMode", "Seçim yöntemi", "select", { items: ["automatic", "manual", "popular", "new"] }), f("content", "provider", "Provider"), f("root", "category", "Kategori"), f("content", "gameCodes", "Manuel oyun kodları", "tags"), f("content", "limit", "Limit", "number", { min: 1 }), f("content", "authenticatedOnly", "Yalnız giriş yapanlar", "switch")] },
  { type: "provider-showcase", slug: "provider-showcases", title: "Sağlayıcı Vitrini", singular: "Sağlayıcı vitrini", description: "Provider logo, arka plan, CTA ve öne çıkan oyunlar.", icon: "tabler-building-store", accent: "info", fields: [...common, ...media, f("content", "providerCode", "Provider kodu", "text", { required: true }), f("content", "logo", "Logo URL", "image"), f("content", "gameCodes", "Öne çıkan oyunlar", "tags"), ...cta] },
  { type: "battle-showcase", slug: "battle-showcases", title: "Battle Vitrini", singular: "Battle vitrini", description: "Turnuva bağlantısı, ödül metni, sayaç ve CTA.", icon: "tabler-swords", accent: "error", fields: [...common, ...media, f("content", "battleId", "Battle / turnuva ID"), f("content", "prizeText", "Ödül metni"), f("content", "showCountdown", "Sayaç göster", "switch"), ...schedule, ...cta] },
  { type: "ui-copy", slug: "ui-copy", title: "UI Metinleri", singular: "UI metni", description: "Namespace ve anahtar bazlı yerelleştirilmiş arayüz metinleri.", icon: "tabler-language", accent: "secondary", fields: [f("content", "namespace", "Namespace", "text", { required: true }), f("root", "slug", "Anahtar", "text", { required: true }), f("root", "title", "Kısa metin", "text", { required: true }), f("root", "description", "Uzun metin", "textarea"), f("root", "locale", "Dil", "select", { items: ["tr", "en", "de", "ru"] }), f("content", "allowHtml", "Güvenli HTML", "switch"), f("content", "note", "Yönetici açıklaması", "textarea")] },
  { type: "crypto-staking", slug: "crypto-staking", title: "Crypto Staking", singular: "Staking ürünü", description: "Coin, getiri, vade ve risk bilgileri.", icon: "tabler-coins", accent: "warning", fields: [...common, f("content", "coin", "Coin", "text", { required: true }), f("content", "apr", "APR / APY (%)", "number", { min: 0 }), f("content", "termDays", "Vade (gün)", "number", { min: 0 }), f("content", "minimum", "Minimum", "number", { min: 0 }), f("content", "maximum", "Maksimum", "number", { min: 0 }), f("content", "precision", "Hassasiyet", "number", { min: 0 }), f("content", "badge", "Rozet"), f("content", "risk", "Risk metni", "textarea"), f("content", "active", "Aktif", "switch")] },
  { type: "crypto-swap", slug: "crypto-swap", title: "Crypto Swap", singular: "Swap çifti", description: "Swap çiftleri, ücret, limit ve quote süreleri.", icon: "tabler-arrows-exchange", accent: "primary", fields: [...common, f("content", "fromCoin", "Kaynak coin", "text", { required: true }), f("content", "toCoin", "Hedef coin", "text", { required: true }), f("content", "fee", "Fee (%)", "number", { min: 0 }), f("content", "minimum", "Minimum", "number", { min: 0 }), f("content", "maximum", "Maksimum", "number", { min: 0 }), f("content", "precision", "Hassasiyet", "number", { min: 0 }), f("content", "quoteSeconds", "Quote süresi (sn)", "number", { min: 1 }), f("content", "active", "Aktif", "switch")] },
  { type: "crypto-futures-display", slug: "crypto-futures", title: "Crypto Futures", singular: "Futures marketi", description: "Market, kaldıraç, pozisyon, fee ve risk ayarları.", icon: "tabler-chart-candle", accent: "error", fields: [...common, f("content", "symbol", "Market / sembol", "text", { required: true }), f("content", "leverages", "Kaldıraç seçenekleri", "tags"), f("content", "minimumPosition", "Minimum pozisyon", "number", { min: 0 }), f("content", "fee", "Fee (%)", "number", { min: 0 }), f("content", "risk", "Risk metni", "textarea"), f("content", "visible", "Görünür", "switch")] },
  { type: "crypto-lootbox-display", slug: "crypto-lootboxes", title: "Crypto Lootboxes", singular: "Lootbox vitrini", description: "Gerçek Box kaydına bağlı kart, seviye ve fiyat gösterimi.", icon: "tabler-box", accent: "warning", fields: [...common, ...media, f("content", "boxId", "Box kayıt ID", "text", { required: true }), f("rules", "minimumLevel", "Minimum seviye", "number", { min: 0 }), f("content", "showPrice", "Fiyatı göster", "switch"), f("content", "badge", "Rozet")] },
]

export const contentTypes = configs
export const contentTypeBySlug = Object.fromEntries(configs.map(item => [item.slug, item])) as Record<string, ContentTypeConfig>
export const contentTypeByValue = Object.fromEntries(configs.map(item => [item.type, item])) as Record<string, ContentTypeConfig>
